Change wrtctl to read commands from a file.
Removes the -s and -c options, replacing them with -f.  Reading from
stdin is also supported.  Justification is that it will probably be
quite rare to only send one command at a time and bringing up the entire
network stack each time is a waste.

New format for commands is:
<subsystem>:<command>

Test cases have been updated and enhanced.

diff --git a/test/test.sh.in b/test/test.sh.in
--- a/test/test.sh.in
+++ b/test/test.sh.in
@@ -42,210 +42,227 @@ grep_file() {
         return $?
     elif ! grep -E "${str}" ${2} >/dev/null; then
         echo
-        echo "ERROR:  Did not find '$str' in $2";
+        echo "   ERROR:  Did not find '$str' in $2";
         return 1
     fi
 }
 
 run_test() {
-    local exp_rc
-    local exp_str
-    local rc
+    local t=$1
+    local r=$2
+    local str=$3
+    local cmd=$4
+    local exe=$5
 
-    exp_rc=$1;shift
-    exp_str=$1;shift
 
-    "$@" &> test.log;rc=$?
+    case "${t}" in
+        "run")
+            printf "${cmd}" | ${exe} &>test.log;rc=$?
+            if [[ ${rc} -ne ${r} ]]; then
+                echo
+                echo "   ERROR:  Return ${rc} != ${r}"
+                echo "     Executable: ${exe}"
+                echo "     Command:    ${cmd}"
+                return 1
+            fi
 
-    if [[ ${rc} -ne ${exp_rc} ]]; then
-        echo
-        echo "   ERROR:  Return ${rc} != ${exp_rc}"
-        echo "Command line was:  $@"
-        return 1
-    fi
+            if [ -n "${str}" ]; then
+                if ! grep_file "${str}" test.log; then
+                    echo
+                    echo "   ERROR:  Unexpected output in test.log"
+                    echo "     Expected: ${str}"
+                    echo "     Executable: ${exe}"
+                    echo "     Command:    ${cmd}"
+                    return 1
+                fi
+            fi
+            ;;
 
-    if ! grep_file "${exp_str}" test.log; then
-        echo "Command line was:  $@"
-        return 1
-    fi
-    
+        "grep")
+            if ! grep_file "${str}" "${cmd}"; then
+                echo "   ERROR:  Unexpected output in file ${cmd}"
+                echo "     Expected: ${str}"
+                return 1
+            fi
+            ;; 
+
+        "exist")
+            [ -s "${str}" ]; rc=$?
+            if [[ ${rc} -ne ${r} ]]; then
+                echo
+                echo "   ERROR:  File (not)expected: ${str}"
+                return 1
+            fi
+            ;;
+    esac
     return 0
 }
 
 fail() {
     echo "Failed"
     kill ${wrtctld_pid} &>/dev/null
+    wait ${wrtctld_pid}
     exit 1
 }
 
-test_uci_cmd_get() {
-    local p="${wrtctlp} $@ -s uci -c "
+uci_tests=(
+# uci:get
+    "run"   0   "test\.cfg[0-9]+\.first_opt=1"              "uci:get test..first_opt"
+    "run"   0   "test\.@anon_section\[0\].first_opt=1"      "uci:get test.@anon_section[0].first_opt"
+    "run"   0   "test\.@anon_section\[1\].first_opt=3"      "uci:get test.@anon_section[1].first_opt"
+    "run"   0   "test\.section_name.optA=A"                 "uci:get test.section_name.optA"
+    "run"   1   "3, test.blah.blah not found"               "uci:get test.blah.blah"
+    "run"   1   "3, uci_lookup_ptr: Entry not found"        "uci:get blah.blah.blah"
+    "run"   0   ""                                          "uci:set test..first_opt=was_set"
+# uci:set uci:commit
+    "grep"  0   "first_opt=was_set"                         "${WRTCTL_UCI_SAVEDIR}/test"
+    "run"   0   ""                                          "uci:set test..first_opt=was_set2"
+    "grep"  0   "first_opt=was_set2"                        "${WRTCTL_UCI_SAVEDIR}/test"
+    "run"   0   ""                                          "uci:commit"
+    "run"   0   "test\.cfg[0-9]+\.first_opt=was_set2"       "uci:get test..first_opt"
+    "grep"  0   "'first_opt' 'was_set2'"                    "${WRTCTL_UCI_CONFDIR}/test"
+    "run"   0   ""                                          "uci:set test.@anon_section[0].first_opt=set3"
+    "grep"  0   "first_opt=set3"                            "${WRTCTL_UCI_SAVEDIR}/test"
+    "run"   0   ""                                          "uci:commit test"
+    "run"   0   "test\.@anon_section\[0\].first_opt=set3"   "uci:get test.@anon_section[0].first_opt"
+    "run"   1   "3, uci_cmd_set:uci_fill_section: Entry not found"
+                                                            "uci:set blah..first_opt=blah"
+    "run"   1   "2, uci_set: Invalid argument"              "uci:set test.blah.first_opt=blah"
+    "run"   1   "3, uci_load_package: Entry not found"      "uci:commit blah"
+    "exist" 1   "${WRTCTL_UCI_SAVEDIR}/blah"                ""
+    "exist" 1   "${WRTCTL_UCI_CONFDIR}/blah"                ""
+# uci:revert
+    "run"   0   ""                                          "uci:set test..first_opt=was_set"
+    "run"   0   ""                                          "uci:revert"
+    "exist" 1   "${WRTCTL_UCI_SAVEDIR}/test"                ""
+    "run"   0   ""                                          "uci:set test..first_opt=was_set2"
+    "run"   0   ""                                          "uci:revert test"
+    "exist" 1   "${WRTCTL_UCI_SAVEDIR}/test"                ""
+    "run"   0   ""                                          "uci:set test..first_opt=was_set2"
+    "run"   0   ""                                          "uci:revert test..first_opt"
+    "exist" 1   "${WRTCTL_UCI_SAVEDIR}/test"                ""
+    #"run"   0   "test\.cfg[0-9a-z]+\.first_opt=set3"        "uci:get test..first_opt"
+    "run"   0   ""                                          "uci:commit"
+    "run"   0   "test\.section_name.optA=A"                 "uci:get test.section_name.optA"
+)
 
-    printf "%-50s" "Testing UCI get commands..."
-    run_test 0 "test\.cfg[0-9]+\.first_opt=1" $p 'get test..first_opt'  || fail
-    run_test 0 "test\.@anon_section\[0\].first_opt=1" $p 'get test.@anon_section[0].first_opt'  || fail
-    run_test 0 "test\.@anon_section\[1\].first_opt=3" $p 'get test.@anon_section[1].first_opt'  || fail
-    run_test 0 "test\.section_name.optA=A" $p 'get test.section_name.optA'  || fail
-    run_test 1 "Server UCI Error:  3, test.blah.blah not found" $p 'get test.blah.blah'  || fail
-    run_test 1 "Server UCI Error:  3, uci_lookup_ptr: Entry not found" $p 'get blah.blah.blah'  || fail
-    echo "Success"
-    return 0
+daemon_tests=(
+    "run"   0   "^[0-9]+$"                                  "daemon:ping"
+    "run"   0   "Rebooting\.\.\."                           "daemon:reboot"
+)
+
+daemon_bad_path_tests=(
+    "run"   1   "2, access:  No such file or directory"     "daemon:reboot"
+)
+
+daemon_noexec_tests=(
+    "run"   1   "13, access:  Permission denied"            "daemon:reboot"
+)
+
+sys_tests=(
+    "run"   0   "initd.test start success"                  "sys:initd initd.test start"
+    "grep"  0   "initd.test: start"                         "${WRTCTL_SYS_INITD_DIR}/log"
+    "run"   0   "initd.test stop success"                   "sys:initd initd.test stop"
+    "grep"  0   "initd.test: stop"                          "${WRTCTL_SYS_INITD_DIR}/log"
+    "run"   1   "Invalid argument to sys\.initd"            "sys:initd initd.test invalid"
+    "run"   1   "22, Invalid init command"                  "sys:initd initd.test startblah"
+    "run"   1   "1, access:  No such file or directory"     "sys:initd nofile start"
+    "run"   1   "1, access:  No such file or directory"     "sys:initd /this/bad/path start"
+)
+
+sys_noexe_tests=(
+    "run"   1   "1, access:  Permission denied"             "sys:initd initd.test start"
+)
+
+run_uci_tests() {
+    local i
+
+    printf "%-50s" "Testing UCI commands"
+    for ((i=0; i<${#uci_tests[@]}; i+=4)); do
+        run_test \
+            "${uci_tests[i]}" \
+            "${uci_tests[i+1]}" \
+            "${uci_tests[i+2]}" \
+            "${uci_tests[i+3]}" \
+            "${wrtctlp} -f - $@" \
+            || fail
+    done
+    echo "OK"
 }
 
-test_uci_cmd_set_commit() {
-    local p="${wrtctlp} $@ -s uci -c"
-    local path="${WRTCTL_UCI_CONFDIR}/test"
-    local spath="${WRTCTL_UCI_SAVEDIR}/test"
-    
-    printf "%-50s" "Testing UCI set and commit commands..."
-
-    run_test 0 "" $p 'set test..first_opt=was_set' || fail
-    grep_file "first_opt=was_set" ${spath} || fail
-    run_test 0 "" $p 'set test..first_opt=was_set2' || fail
-    grep_file "first_opt=was_set2" ${spath} || fail
-    run_test 0 "" $p 'commit' || fail
-    grep_file "option 'first_opt' 'was_set2'" ${path} || fail
-    
-    run_test 0 "" $p 'set test..first_opt=was_set3' || fail
-    grep_file "first_opt=was_set3" ${spath} || fail
-    run_test 0 "" $p 'commit' || fail
-    run_test 0 "" $p 'commit' || fail
-    grep_file "option 'first_opt' 'was_set3'" ${path} || fail
-     
-    run_test 0 "" $p 'set test.@anon_section[0].first_opt=was_set_again' || fail
-    grep_file "first_opt=was_set_again" ${spath} || fail
-    run_test 0 "" $p 'commit test' || fail
-    grep_file "option 'first_opt' 'was_set_again'" ${path} || fail
-
-    run_test 0 "" $p 'set test.section_name.optA=was_set' || fail
-    grep_file "optA=was_set" ${spath} || fail
-    run_test 0 "" $p 'commit' || fail
-    grep_file "option 'optA' 'was_set'" ${path} || fail
-
-
-    run_test 1 "Server UCI Error:  3, uci_cmd_set:uci_fill_section: Entry not found" $p 'set blah..first_opt=blah' || fail
-    run_test 1 "Server UCI Error:  2, uci_set: Invalid argument" $p 'set test.blah.first_opt=blah' || fail
-    run_test 1 "Server UCI Error:  3, uci_load_package: Entry not found" $p 'commit blah' || fail
-    if grep 'blah' ${spath} >/dev/null || grep 'blah' ${path} >/dev/null; then
-        echo "Invalid commands still wrote 'blah' to ${spath} and/or ${path}"
-        return 1
-    fi
-    echo "Success"
-}
-
-test_uci_cmd_revert() {
-    local p="${wrtctlp} $@ -s uci -c"
-    
-    printf "%-50s" "Testing UCI revert..."
-
-    
-    run_test 0 "" $p 'set test..first_opt=was_set' || fail
-    run_test 0 "" $p 'revert' || fail
-    if [ -s "${WRTCTL_UCI_SAVEDIR}/test" ]; then
-        echo "ERROR:  ${WRTCTL_UCI_SAVEDIR}/test was not reverted"
-        exit 1
-    fi
-    
-    run_test 0 "" $p 'set test..first_opt=was_set2' || fail
-    run_test 0 "" $p 'revert test' || fail
-    if [ -s "${WRTCTL_UCI_SAVEDIR}/test" ]; then
-        echo "ERROR:  ${WRTCTL_UCI_SAVEDIR}/test was not reverted"
-        exit 1
-    fi
-
-    run_test 0 "" $p 'set test..first_opt=was_set2' || fail
-    run_test 0 "" $p 'revert test..first_opt' || fail
-    if [ -s "${WRTCTL_UCI_SAVEDIR}/test" ]; then
-        echo "ERROR:  ${WRTCTL_UCI_SAVEDIR}/test was not reverted"
-        exit 1
-    fi
-
-    run_test 0 "" $p 'commit' || fail
-    if grep "'option 'first_opt' 'was_set2'" ${WRTCTL_UCI_CONFDIR}; then
-        echo "ERROR:  ${WRTCTL_UCI_CONFDIR} got reverted changes."
-        exit 1
-    fi
-    echo "Success"
-    return 0
-}
-
-test_sys_cmd_ping() {
-    local p="${wrtctlp} $@ -s daemon -c ping"
-    printf "%-50s" "Testing DAEMON ping..."
-    run_test 0 "^[0-9]+$" $p || fail
-    echo "Success"
-}
-
-test_sys_cmd_reboot() {
-    local p="${wrtctlp} $@ -s daemon -c reboot"
+run_daemon_tests() {
+    local i
     local op=${WRTCTL_SYS_SHUTDOWN_PATH}
-    local lpath="${WRTCTL_SYS_INITD_DIR}/log"
 
-    chmod +x ${op}
-    rm -f ${WRTCTL_SYS_INITD_DIR}/log
+    printf "%-50s" "Testing daemon commands"
    
-    printf "%-50s" "Testing Daemon reboot..."
-    run_test 0 "Rebooting\.\.\." $p || fail
-    sleep 6 # Wait for child to write the file
-    grep_file "shutdown: -r now" ${lpath} || fail
-    rm -f ${WRTCTL_SYS_INITD_DIR}/log
+    chmod +x ${op}
+    for ((i=0; i<${#daemon_tests[@]}; i+=4)); do
+        run_test \
+            "${daemon_tests[i]}" \
+            "${daemon_tests[i+1]}" \
+            "${daemon_tests[i+2]}" \
+            "${daemon_tests[i+3]}" \
+            "${wrtctlp} -f - $@" \
+            || fail
+    done
 
+    stop_daemon
     export WRTCTL_SYS_SHUTDOWN_PATH=/path/does/not/exist
     start_daemon
-    run_test 1 "Server Daemon Error:  2, access:  No such file or directory" $p || fail
-    [[ ! -f ${WRTCTL_SYS_INITD_DIR}/log ]] || fail
-    stop_daemon
-    
+    for ((i=0; i<${#daemon_bad_path_tests[@]}; i+=4)); do
+        run_test \
+            "${daemon_bad_path_tests[i]}" \
+            "${daemon_bad_path_tests[i+1]}" \
+            "${daemon_bad_path_tests[i+2]}" \
+            "${daemon_bad_path_tests[i+3]}" \
+            "${wrtctlp} -f - $@" \
+            || fail
+    done
 
+    stop_daemon
     export WRTCTL_SYS_SHUTDOWN_PATH=${op}
     start_daemon
     chmod -x ${op}
-    run_test 1 "Server Daemon Error:  13, access:  Permission denied" $p || fail
-    chmod +x ${op}
-    [[ ! -f ${WRTCTL_SYS_INITD_DIR}/log ]] || fail
-    echo "Success"
-
+    for ((i=0; i<${#daemon_noexe_tests[@]}; i+=4)); do
+        run_test \
+            "${daemon_noexe_tests[i]}" \
+            "${daemon_noexe_tests[i+1]}" \
+            "${daemon_noexe_tests[i+2]}" \
+            "${daemon_noexe_tests[i+3]}" \
+            "${wrtctlp} -f - $@" \
+            || fail
+    done
+    echo "OK"
 }
 
-test_sys_cmd_initd() {
-    local p="${wrtctlp} $@ -s sys -c "
-    local lpath="${WRTCTL_SYS_INITD_DIR}/log"
+run_sys_tests() {
+    local i 
     local it="${WRTCTL_SYS_INITD_DIR}/initd.test"
-
-    printf "%-50s" "Testing SYS initd..."
-    chmod +x ${it}
-    rm -f ${lpath} > /dev/null
-    run_test 0 "initd.test start success" $p 'initd initd.test start' || fail
-    grep_file "initd.test: start" ${lpath} || fail
-
-    rm -f ${lpath} > /dev/null
-    run_test 0 "initd.test stop success" $p 'initd initd.test stop' || fail
-    grep_file "initd.test: stop" ${lpath} || fail
-
-    rm -f ${lpath} > /dev/null
-    run_test 0 "initd.test restart success" $p 'initd initd.test restart' || fail
-    grep_file "initd.test: restart" ${lpath} || fail
-
    
-    rm -f ${lpath} > /dev/null
-    run_test 1 "Invalid argument to sys\.initd" $p 'initd initd.test invalid' || fail
-    run_test 1 "Server SysCmds Error:  22, Invalid init command" \
-        $p 'initd initd.test restartblah' || fail
-    
+    chmod +x ${it}
+    for ((i=0; i<${#sys_tests[@]}; i+=4)); do
+        run_test \
+            "${sys_tests[i]}" \
+            "${sys_tests[i+1]}" \
+            "${sys_tests[i+2]}" \
+            "${sys_tests[i+3]}" \
+            "${wrtctlp} -f - $@" \
+            || fail
+    done
+
     chmod -x ${it}
-    run_test 1 "Server SysCmds Error:  1, access:  Permission denied" \
-        $p 'initd initd.test stop' || fail
-    chmod +x ${it}
-   
-    run_test 1 "Server SysCmds Error:  1, access:  No such file or directory" \
-        $p 'initd nofile stop' || fail
-    run_test 1 "Server SysCmds Error:  1, access:  No such file or directory" \
-        $p 'initd /invalid/path/nofile stop' || fail
-    [[ ! -f ${lpath} ]] || fail
-
-    echo "Success"
+    for ((i=0; i<${#sys_noexe_tests[@]}; i+=4)); do
+        run_test \
+            "${sys_noexe_tests[i]}" \
+            "${sys_noexe_tests[i+1]}" \
+            "${sys_noexe_tests[i+2]}" \
+            "${sys_noexe_tests[i+3]}" \
+            "${wrtctlp} -f - $@" \
+            || fail
+    done
+    echo "OK"
 }
-
 
 start_daemon() {
     local args=""
@@ -261,41 +278,36 @@ start_daemon() {
 }
 
 stop_daemon() {
-    kill ${wrtctld_pid} &>/dev/null || fail
+    if ! killall lt-wrtctld; then
+        echo "ERROR:  Failed to killall lt-wrtctld"
+        fail
+    fi
+    wait
 }
 
 start_daemon
 create_conf_file
 
 if [ @STUNNEL@ -eq 0 ]; then
-    test_uci_cmd_get
-    test_uci_cmd_set_commit
-    test_uci_cmd_revert
-    test_sys_cmd_ping
-    #test_sys_cmd_reboot
-    test_sys_cmd_initd
+    run_uci_tests
+    run_daemon_tests
+    run_sys_tests
 else 
     echo
     echo "Testing without stunnel wrapper"
     echo
-    test_uci_cmd_get -n
-    test_uci_cmd_set_commit -n
-    test_uci_cmd_revert -n
-    test_sys_cmd_ping -n
-    #test_sys_cmd_reboot -n
-    test_sys_cmd_initd -n
+    run_uci_tests -n
+    run_daemon_tests -n
+    run_sys_tests -n
     stop_daemon
     echo
     echo "Testing with stunnel wrapper"
     echo
-    start_daemon
     create_conf_file
-    test_uci_cmd_get -k ${key_path}
-    test_uci_cmd_set_commit -k ${key_path}
-    test_uci_cmd_revert -k ${key_path}
-    test_sys_cmd_ping -k ${key_path}
-    #test_sys_cmd_reboot
-    test_sys_cmd_initd -k ${key_path}
+    start_daemon
+    run_uci_tests -k "${key_path}"
+    run_daemon_tests -k "${key_path}"
+    run_sys_tests -k "${key_path}"
 fi
 stop_daemon
 exit 0
